USE DATABASE HOSPITAL_ER_DB;

CREATE OR REPLACE ROLE ER_ADMIN;
CREATE OR REPLACE ROLE ER_ANALYST;
CREATE OR REPLACE ROLE ER_EXECUTIVE;

GRANT ROLE ER_ANALYST TO ROLE ER_ADMIN;
GRANT ROLE ER_EXECUTIVE TO ROLE ER_ADMIN;

GRANT USAGE ON WAREHOUSE ER_ANALYTICS_WH TO ROLE ER_ANALYST;
GRANT USAGE ON DATABASE HOSPITAL_ER_DB TO ROLE ER_ANALYST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE HOSPITAL_ER_DB TO ROLE ER_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA HOSPITAL_ER_DB.CORE TO ROLE ER_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA HOSPITAL_ER_DB.CORE TO ROLE ER_ANALYST;

CREATE OR REPLACE MASKING POLICY MASK_COST_USD AS (val NUMBER) RETURNS NUMBER ->
  CASE
    WHEN CURRENT_ROLE() IN ('ER_ADMIN') THEN val
    ELSE ROUND(val, -2) -- mask to nearest hundred for non-admin roles
  END;

ALTER TABLE HOSPITAL_ER_DB.CORE.FACT_EMERGENCY_RESPONSE
  MODIFY COLUMN cost_usd
  SET MASKING POLICY MASK_COST_USD;

CREATE OR REPLACE ROW ACCESS POLICY RAP_STATE_FILTER AS (state_col STRING) RETURNS BOOLEAN ->
  CASE
    WHEN CURRENT_ROLE() = 'ER_EXECUTIVE' THEN state_col = 'CA'
    ELSE TRUE
  END;

ALTER TABLE HOSPITAL_ER_DB.CORE.DIM_HOSPITAL
  ADD ROW ACCESS POLICY RAP_STATE_FILTER ON (state);

CREATE OR REPLACE TAG DATA_CLASSIFICATION ALLOWED_VALUES 'PUBLIC', 'INTERNAL', 'SENSITIVE';

ALTER TABLE HOSPITAL_ER_DB.CORE.FACT_EMERGENCY_RESPONSE
  SET TAG DATA_CLASSIFICATION = 'SENSITIVE';

ALTER TABLE HOSPITAL_ER_DB.CORE.DIM_HOSPITAL
  SET TAG DATA_CLASSIFICATION = 'INTERNAL';
